global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'variant-a'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'variant-c'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'variant-d'
    static_configs:
      - targets: ['host.docker.internal:8083']

